# conda environment configuration for snakemake
name: Variant Calling 
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - trim-galore=0.6.6
    - bowtie2=2.3.5.1
    - picard=2.24.2
    - samtools=1.7
    - gatk4=4.1.9.0
